production:
  adapter:  mysql2
  host:     192.168.1.104
  encoding: utf8
  reconnect: false
  database: fortune_telling_development
  pool: 5
  username: user1
  password: user1

development:
  adapter:  sqlite3
  database: db/visitor_log.sqlite3
